import type { Formula } from '../types';
import { chapterSlug, slugify } from './chapters';

// High-value CAT QA formulas, seeded on first run. Each carries whenToUse and
// commonTrap — the parts that turn a formula list into a usable revision tool.
// chapterId values are computed with chapterSlug so they always match the
// seeded chapters.

interface SeedFormula {
  chapter: [topicGroup: string, name: string]; // within QA
  title: string;
  latex: string;
  plainText: string;
  description: string;
  whenToUse: string;
  commonTrap: string;
}

const QA: SeedFormula[] = [
  // ---- Arithmetic: Percentages ----
  {
    chapter: ['Arithmetic', 'Percentages'],
    title: 'Percentage change',
    latex: '\\%\\text{ change} = \\dfrac{\\text{new} - \\text{old}}{\\text{old}} \\times 100',
    plainText: '% change = (new - old)/old * 100',
    description: 'Relative change of a quantity.',
    whenToUse: 'Any increase/decrease expressed as a percentage of the original.',
    commonTrap: 'Dividing by the new value instead of the original.',
  },
  {
    chapter: ['Arithmetic', 'Percentages'],
    title: 'Successive percentage change',
    latex: 'a + b + \\dfrac{ab}{100}',
    plainText: 'net% = a + b + ab/100',
    description: 'Net effect of two successive changes of a% then b% (signed).',
    whenToUse: 'Two back-to-back changes (e.g. price up 20% then down 10%).',
    commonTrap: 'Just adding a + b and forgetting the ab/100 term (sign matters).',
  },
  {
    chapter: ['Arithmetic', 'Percentages'],
    title: 'Fraction ↔ percentage anchors',
    latex: '\\tfrac{1}{n}\\times 100',
    plainText: '1/n as a percentage',
    description: 'Memorised anchors: 1/8=12.5%, 1/6≈16.67%, 1/7≈14.28%.',
    whenToUse: 'Fast mental conversion in DI and percentage problems.',
    commonTrap: 'Confusing 1/6 (16.67%) with 1/7 (14.28%).',
  },
  // ---- Arithmetic: Profit, Loss & Discount ----
  {
    chapter: ['Arithmetic', 'Profit, Loss & Discount'],
    title: 'Profit percentage',
    latex: '\\text{Profit\\%} = \\dfrac{SP - CP}{CP} \\times 100',
    plainText: 'Profit% = (SP-CP)/CP * 100',
    description: 'Profit as a percentage of cost price.',
    whenToUse: 'Given cost and selling price.',
    commonTrap: 'Taking profit% on SP; it is always on CP unless stated.',
  },
  {
    chapter: ['Arithmetic', 'Profit, Loss & Discount'],
    title: 'Discount on marked price',
    latex: 'SP = MP\\left(1 - \\tfrac{d}{100}\\right)',
    plainText: 'SP = MP*(1 - d/100)',
    description: 'Selling price after a discount d% on marked price.',
    whenToUse: 'Marked price and discount known.',
    commonTrap: 'Applying discount to CP instead of MP.',
  },
  {
    chapter: ['Arithmetic', 'Profit, Loss & Discount'],
    title: 'False weight gain',
    latex: '\\text{Gain\\%} = \\dfrac{\\text{true} - \\text{false}}{\\text{false}} \\times 100',
    plainText: 'gain% = (true - false weight)/false weight * 100',
    description: 'Shopkeeper using a lighter weight than claimed.',
    whenToUse: 'Dishonest-dealer problems selling at cost price.',
    commonTrap: 'Dividing by the true weight instead of the false weight used.',
  },
  // ---- Arithmetic: Simple & Compound Interest ----
  {
    chapter: ['Arithmetic', 'Simple & Compound Interest'],
    title: 'Simple interest',
    latex: 'SI = \\dfrac{P \\cdot R \\cdot T}{100}',
    plainText: 'SI = P*R*T/100',
    description: 'Interest that does not compound.',
    whenToUse: 'Interest on a fixed principal at rate R% for T years.',
    commonTrap: 'Mismatched time units (months vs years).',
  },
  {
    chapter: ['Arithmetic', 'Simple & Compound Interest'],
    title: 'Compound amount',
    latex: 'A = P\\left(1 + \\tfrac{R}{100}\\right)^{T}',
    plainText: 'A = P(1 + R/100)^T',
    description: 'Amount after compound interest.',
    whenToUse: 'Interest compounding annually.',
    commonTrap: 'For non-annual compounding, adjust both rate and periods.',
  },
  {
    chapter: ['Arithmetic', 'Simple & Compound Interest'],
    title: 'CI − SI for 2 years',
    latex: 'CI - SI = P\\left(\\tfrac{R}{100}\\right)^{2}',
    plainText: 'CI - SI (2 yrs) = P(R/100)^2',
    description: 'Difference between CI and SI over two years.',
    whenToUse: 'Quickly comparing CI and SI for exactly two years.',
    commonTrap: 'Using this for periods other than 2 years.',
  },
  // ---- Arithmetic: Ratio & Proportion ----
  {
    chapter: ['Arithmetic', 'Ratio & Proportion'],
    title: 'Componendo–dividendo',
    latex: '\\dfrac{a}{b} = \\dfrac{c}{d} \\Rightarrow \\dfrac{a+b}{a-b} = \\dfrac{c+d}{c-d}',
    plainText: 'a/b = c/d => (a+b)/(a-b) = (c+d)/(c-d)',
    description: 'Transformation of proportions.',
    whenToUse: 'Simplifying equations where a ratio equals a ratio.',
    commonTrap: 'Applying when a = b (denominator becomes zero).',
  },
  {
    chapter: ['Arithmetic', 'Ratio & Proportion'],
    title: 'Sharing in a ratio',
    latex: '\\text{share}_i = T \\cdot \\dfrac{r_i}{\\sum r}',
    plainText: 'share = Total * r_i / sum(r)',
    description: 'Divide a total in a given ratio.',
    whenToUse: 'Partnerships, mixtures, dividing amounts.',
    commonTrap: 'Forgetting to reduce ratios to the same time base (partnerships).',
  },
  // ---- Arithmetic: Averages & Alligation ----
  {
    chapter: ['Arithmetic', 'Averages & Alligation'],
    title: 'Alligation rule',
    latex: '\\dfrac{q_c}{q_d} = \\dfrac{P_d - P_m}{P_m - P_c}',
    plainText: 'cheaper:dearer = (Pd - Pm):(Pm - Pc)',
    description: 'Ratio of quantities from mean price.',
    whenToUse: 'Mixing two grades to hit a target average.',
    commonTrap: 'Swapping the numerator/denominator differences.',
  },
  {
    chapter: ['Arithmetic', 'Averages & Alligation'],
    title: 'Average',
    latex: '\\bar{x} = \\dfrac{\\sum x_i}{n}',
    plainText: 'average = sum/n',
    description: 'Arithmetic mean.',
    whenToUse: 'Any mean of n values.',
    commonTrap: 'Averaging averages without weighting by counts.',
  },
  // ---- Arithmetic: Time, Speed & Distance ----
  {
    chapter: ['Arithmetic', 'Time, Speed & Distance'],
    title: 'Speed–distance–time',
    latex: '\\text{Speed} = \\dfrac{\\text{Distance}}{\\text{Time}}',
    plainText: 'speed = distance/time',
    description: 'Core relation.',
    whenToUse: 'Everything in motion problems.',
    commonTrap: 'Mixing units (km/h vs m/s): multiply km/h by 5/18 for m/s.',
  },
  {
    chapter: ['Arithmetic', 'Time, Speed & Distance'],
    title: 'Average speed (equal distance)',
    latex: '\\bar{v} = \\dfrac{2 v_1 v_2}{v_1 + v_2}',
    plainText: 'avg speed = 2*v1*v2/(v1+v2)',
    description: 'Harmonic mean for equal distances at two speeds.',
    whenToUse: 'Same distance covered at two different speeds.',
    commonTrap: 'Taking the plain average of the two speeds.',
  },
  {
    chapter: ['Arithmetic', 'Time, Speed & Distance'],
    title: 'Relative speed',
    latex: 'v_{rel} = v_1 \\pm v_2',
    plainText: 'relative speed = v1 ± v2',
    description: 'Subtract for same direction, add for opposite.',
    whenToUse: 'Trains, boats, two moving bodies.',
    commonTrap: 'Using the wrong sign for direction; include train lengths.',
  },
  {
    chapter: ['Arithmetic', 'Time, Speed & Distance'],
    title: 'Boats & streams',
    latex: 'v_{down} = b + s,\\quad v_{up} = b - s',
    plainText: 'downstream=b+s, upstream=b-s',
    description: 'Boat speed b, stream s.',
    whenToUse: 'Upstream/downstream problems.',
    commonTrap: 'Confusing which is boat speed vs stream speed.',
  },
  // ---- Arithmetic: Time & Work ----
  {
    chapter: ['Arithmetic', 'Time & Work'],
    title: 'Combined work rate',
    latex: '\\dfrac{1}{T} = \\dfrac{1}{a} + \\dfrac{1}{b}',
    plainText: '1/T = 1/a + 1/b',
    description: 'Two workers together.',
    whenToUse: 'Combined time when each alone takes a, b.',
    commonTrap: 'Adding times instead of rates.',
  },
  {
    chapter: ['Arithmetic', 'Time & Work'],
    title: 'Work = rate × time',
    latex: 'W = R \\times T',
    plainText: 'Work = Rate * Time',
    description: 'Fundamental work identity (use LCM of days as total work).',
    whenToUse: 'Set total work = LCM to avoid fractions.',
    commonTrap: 'Not keeping man-days constant when workers change.',
  },
  // ---- Arithmetic: Mixtures ----
  {
    chapter: ['Arithmetic', 'Mixtures'],
    title: 'Repeated replacement',
    latex: 'x\\left(1 - \\tfrac{r}{V}\\right)^{n}',
    plainText: 'final = initial*(1 - r/V)^n',
    description: 'Pure quantity left after replacing r of volume V, n times.',
    whenToUse: 'Milk-and-water repeated removal/replacement.',
    commonTrap: 'Forgetting the volume returns to V after each top-up.',
  },
  // ---- Algebra: Linear Equations ----
  {
    chapter: ['Algebra', 'Linear Equations'],
    title: 'Unique solution condition',
    latex: '\\dfrac{a_1}{a_2} \\neq \\dfrac{b_1}{b_2}',
    plainText: 'a1/a2 != b1/b2 => unique solution',
    description: 'Two linear equations have one solution.',
    whenToUse: 'Deciding consistency of a 2-variable system.',
    commonTrap: 'Confusing with the no-solution / infinite-solution cases.',
  },
  // ---- Algebra: Quadratic Equations ----
  {
    chapter: ['Algebra', 'Quadratic Equations'],
    title: 'Quadratic roots',
    latex: 'x = \\dfrac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}',
    plainText: 'x = (-b ± sqrt(b^2-4ac))/2a',
    description: 'Roots of ax²+bx+c=0.',
    whenToUse: 'When factoring is not obvious.',
    commonTrap: 'Sign errors on b; forgetting a can be negative.',
  },
  {
    chapter: ['Algebra', 'Quadratic Equations'],
    title: 'Sum & product of roots',
    latex: '\\alpha + \\beta = -\\tfrac{b}{a},\\quad \\alpha\\beta = \\tfrac{c}{a}',
    plainText: 'sum=-b/a, product=c/a',
    description: 'Vieta’s relations.',
    whenToUse: 'Building equations from roots or finding symmetric functions.',
    commonTrap: 'Dropping the minus sign on the sum.',
  },
  {
    chapter: ['Algebra', 'Quadratic Equations'],
    title: 'Discriminant',
    latex: 'D = b^2 - 4ac',
    plainText: 'D = b^2 - 4ac',
    description: 'D>0 real distinct, D=0 equal, D<0 complex.',
    whenToUse: 'Nature of roots without solving.',
    commonTrap: 'Assuming D=0 means one root — it is two equal roots.',
  },
  // ---- Algebra: Logarithms ----
  {
    chapter: ['Algebra', 'Logarithms'],
    title: 'Log product & power rules',
    latex: '\\log(xy) = \\log x + \\log y,\\ \\log x^{k} = k\\log x',
    plainText: 'log(xy)=logx+logy; log(x^k)=k logx',
    description: 'Core log identities.',
    whenToUse: 'Expanding or condensing logarithmic expressions.',
    commonTrap: 'Writing log(x+y) = log x + log y (false).',
  },
  {
    chapter: ['Algebra', 'Logarithms'],
    title: 'Change of base',
    latex: '\\log_b a = \\dfrac{\\log_c a}{\\log_c b}',
    plainText: 'log_b(a) = log_c(a)/log_c(b)',
    description: 'Convert between bases.',
    whenToUse: 'Comparing logs of different bases.',
    commonTrap: 'Inverting the ratio.',
  },
  // ---- Algebra: Progressions ----
  {
    chapter: ['Algebra', 'Progressions (AP/GP/HP)'],
    title: 'AP nth term & sum',
    latex: 'a_n = a + (n-1)d,\\quad S_n = \\tfrac{n}{2}\\big(2a + (n-1)d\\big)',
    plainText: 'a_n=a+(n-1)d; S_n=n/2(2a+(n-1)d)',
    description: 'Arithmetic progression.',
    whenToUse: 'Equally spaced sequences.',
    commonTrap: 'Using n instead of n−1 for the nth term.',
  },
  {
    chapter: ['Algebra', 'Progressions (AP/GP/HP)'],
    title: 'GP nth term & sum',
    latex: 'a_n = ar^{n-1},\\quad S_n = a\\dfrac{r^{n}-1}{r-1}',
    plainText: 'a_n=ar^(n-1); S_n=a(r^n-1)/(r-1)',
    description: 'Geometric progression (r≠1).',
    whenToUse: 'Constant-ratio sequences.',
    commonTrap: 'Using the sum formula when r=1.',
  },
  {
    chapter: ['Algebra', 'Progressions (AP/GP/HP)'],
    title: 'Infinite GP sum',
    latex: 'S_\\infty = \\dfrac{a}{1 - r},\\ |r| < 1',
    plainText: 'S_inf = a/(1-r) for |r|<1',
    description: 'Sum of an infinite converging GP.',
    whenToUse: 'Ratio between −1 and 1.',
    commonTrap: 'Applying it when |r| ≥ 1 (diverges).',
  },
  // ---- Algebra: Surds & Indices ----
  {
    chapter: ['Algebra', 'Surds & Indices'],
    title: 'Index laws',
    latex: 'a^{m}\\cdot a^{n} = a^{m+n},\\quad (a^{m})^{n} = a^{mn}',
    plainText: 'a^m*a^n=a^(m+n); (a^m)^n=a^(mn)',
    description: 'Exponent rules.',
    whenToUse: 'Simplifying powers.',
    commonTrap: 'Adding exponents when bases differ.',
  },
  // ---- Algebra: Maxima & Minima ----
  {
    chapter: ['Algebra', 'Maxima & Minima'],
    title: 'AM–GM inequality',
    latex: '\\dfrac{a+b}{2} \\ge \\sqrt{ab}',
    plainText: '(a+b)/2 >= sqrt(ab)',
    description: 'Equality when a=b.',
    whenToUse: 'Minimising sums / maximising products of positives.',
    commonTrap: 'Using it for negative numbers.',
  },
  {
    chapter: ['Algebra', 'Maxima & Minima'],
    title: 'Vertex of a parabola',
    latex: 'x^{*} = -\\dfrac{b}{2a}',
    plainText: 'x* = -b/2a',
    description: 'Extremum of ax²+bx+c.',
    whenToUse: 'Max (a<0) or min (a>0) of a quadratic.',
    commonTrap: 'Assuming it is always a minimum.',
  },
  // ---- Geometry: Triangles ----
  {
    chapter: ['Geometry', 'Triangles'],
    title: 'Heron’s formula',
    latex: 'A = \\sqrt{s(s-a)(s-b)(s-c)},\\ s = \\tfrac{a+b+c}{2}',
    plainText: 'A = sqrt(s(s-a)(s-b)(s-c))',
    description: 'Area from three sides.',
    whenToUse: 'All three sides known, no height.',
    commonTrap: 'Forgetting s is the semi-perimeter.',
  },
  {
    chapter: ['Geometry', 'Triangles'],
    title: 'Pythagoras',
    latex: 'c^{2} = a^{2} + b^{2}',
    plainText: 'c^2 = a^2 + b^2',
    description: 'Right triangle sides.',
    whenToUse: 'Right-angled triangles; recognise triples 3-4-5, 5-12-13.',
    commonTrap: 'Assuming the largest side is a leg, not the hypotenuse.',
  },
  {
    chapter: ['Geometry', 'Triangles'],
    title: 'Area (base × height)',
    latex: 'A = \\tfrac{1}{2} b h',
    plainText: 'A = 1/2 * base * height',
    description: 'Standard triangle area.',
    whenToUse: 'Base and perpendicular height known.',
    commonTrap: 'Using a slant side instead of the perpendicular height.',
  },
  // ---- Geometry: Circles ----
  {
    chapter: ['Geometry', 'Circles'],
    title: 'Circle area & circumference',
    latex: 'A = \\pi r^{2},\\quad C = 2\\pi r',
    plainText: 'A=πr^2; C=2πr',
    description: 'Basic circle metrics.',
    whenToUse: 'Any circle with known radius.',
    commonTrap: 'Mixing radius and diameter.',
  },
  {
    chapter: ['Geometry', 'Circles'],
    title: 'Angle at centre = 2 × at circumference',
    latex: '\\angle_{centre} = 2\\,\\angle_{circumference}',
    plainText: 'central angle = 2 * inscribed angle',
    description: 'Same arc subtends double angle at centre.',
    whenToUse: 'Inscribed-angle problems.',
    commonTrap: 'Applying when angles subtend different arcs.',
  },
  // ---- Geometry: Coordinate Geometry ----
  {
    chapter: ['Geometry', 'Coordinate Geometry'],
    title: 'Distance between points',
    latex: 'd = \\sqrt{(x_2-x_1)^2 + (y_2-y_1)^2}',
    plainText: 'd = sqrt((x2-x1)^2+(y2-y1)^2)',
    description: 'Euclidean distance.',
    whenToUse: 'Length of a segment from coordinates.',
    commonTrap: 'Sign slips inside the squares (they cancel, but order matters for vectors).',
  },
  {
    chapter: ['Geometry', 'Coordinate Geometry'],
    title: 'Section formula',
    latex: '\\left(\\dfrac{mx_2+nx_1}{m+n}, \\dfrac{my_2+ny_1}{m+n}\\right)',
    plainText: 'point dividing in m:n',
    description: 'Point dividing a segment in ratio m:n.',
    whenToUse: 'Internal division of a line segment.',
    commonTrap: 'Swapping which point pairs with m vs n.',
  },
  {
    chapter: ['Geometry', 'Coordinate Geometry'],
    title: 'Slope of a line',
    latex: 'm = \\dfrac{y_2 - y_1}{x_2 - x_1}',
    plainText: 'm = (y2-y1)/(x2-x1)',
    description: 'Gradient between two points.',
    whenToUse: 'Parallel (equal m) / perpendicular (m₁m₂=−1) checks.',
    commonTrap: 'Vertical lines have undefined slope.',
  },
  // ---- Geometry: Mensuration ----
  {
    chapter: ['Geometry', 'Mensuration (2D & 3D)'],
    title: 'Cylinder volume & surface',
    latex: 'V = \\pi r^{2} h,\\quad S = 2\\pi r(r + h)',
    plainText: 'V=πr^2h; S=2πr(r+h)',
    description: 'Right circular cylinder.',
    whenToUse: 'Cylinders, pipes, tanks.',
    commonTrap: 'Using curved surface (2πrh) when total surface is asked.',
  },
  {
    chapter: ['Geometry', 'Mensuration (2D & 3D)'],
    title: 'Sphere volume & surface',
    latex: 'V = \\tfrac{4}{3}\\pi r^{3},\\quad S = 4\\pi r^{2}',
    plainText: 'V=4/3 πr^3; S=4πr^2',
    description: 'Sphere metrics.',
    whenToUse: 'Spheres and hemispheres (halve appropriately).',
    commonTrap: 'Hemisphere total surface is 3πr², not 2πr².',
  },
  {
    chapter: ['Geometry', 'Mensuration (2D & 3D)'],
    title: 'Cone volume',
    latex: 'V = \\tfrac{1}{3}\\pi r^{2} h',
    plainText: 'V = 1/3 πr^2h',
    description: 'Right circular cone.',
    whenToUse: 'Cones; slant l = √(r²+h²) for surface.',
    commonTrap: 'Using height where slant height is needed for surface area.',
  },
  // ---- Geometry: Trigonometry ----
  {
    chapter: ['Geometry', 'Trigonometry'],
    title: 'Pythagorean identity',
    latex: '\\sin^{2}\\theta + \\cos^{2}\\theta = 1',
    plainText: 'sin^2 + cos^2 = 1',
    description: 'Fundamental identity.',
    whenToUse: 'Converting between sine and cosine.',
    commonTrap: 'Sign of the root depends on the quadrant.',
  },
  // ---- Number System: Divisibility & Remainders ----
  {
    chapter: ['Number System', 'Divisibility & Remainders'],
    title: 'Fermat’s little theorem',
    latex: 'a^{p-1} \\equiv 1 \\pmod{p},\\ \\gcd(a,p)=1',
    plainText: 'a^(p-1) ≡ 1 mod p (p prime)',
    description: 'Prime modulus remainder shortcut.',
    whenToUse: 'Large powers mod a prime.',
    commonTrap: 'Requires p prime and a not divisible by p.',
  },
  {
    chapter: ['Number System', 'Divisibility & Remainders'],
    title: 'Remainder of a product',
    latex: '(a \\cdot b) \\bmod n = \\big((a\\bmod n)(b\\bmod n)\\big)\\bmod n',
    plainText: '(ab) mod n = ((a mod n)(b mod n)) mod n',
    description: 'Remainders are multiplicative.',
    whenToUse: 'Breaking big products into manageable remainders.',
    commonTrap: 'Forgetting the final mod n after multiplying.',
  },
  // ---- Number System: HCF & LCM ----
  {
    chapter: ['Number System', 'HCF & LCM'],
    title: 'HCF × LCM = product',
    latex: '\\text{HCF}(a,b)\\times\\text{LCM}(a,b) = a\\times b',
    plainText: 'HCF*LCM = a*b',
    description: 'Only holds for two numbers.',
    whenToUse: 'Finding one when the other three are known.',
    commonTrap: 'Extending to three or more numbers (false).',
  },
  // ---- Number System: Factors & Factorials ----
  {
    chapter: ['Number System', 'Factors & Factorials'],
    title: 'Number of factors',
    latex: 'N = p^{a}q^{b}r^{c} \\Rightarrow (a+1)(b+1)(c+1)',
    plainText: '#factors = (a+1)(b+1)(c+1)',
    description: 'From prime factorisation.',
    whenToUse: 'Counting divisors of N.',
    commonTrap: 'Forgetting to add 1 to each exponent.',
  },
  {
    chapter: ['Number System', 'Factors & Factorials'],
    title: 'Highest power of prime in n!',
    latex: '\\sum_{i\\ge 1} \\left\\lfloor \\dfrac{n}{p^{i}} \\right\\rfloor',
    plainText: 'sum floor(n/p^i)',
    description: 'Legendre’s formula (trailing zeros use p=5).',
    whenToUse: 'Power of a prime dividing n!, trailing zeros.',
    commonTrap: 'Stopping the sum too early while p^i ≤ n.',
  },
  // ---- Number System: Cyclicity ----
  {
    chapter: ['Number System', 'Cyclicity & Unit Digits'],
    title: 'Unit digit cyclicity',
    latex: '\\text{unit}(a^{n}) = \\text{unit}\\big(a^{(n \\bmod 4)}\\big)',
    plainText: 'unit digit repeats every 4 (mostly)',
    description: 'Units digits cycle with period 1, 2 or 4.',
    whenToUse: 'Unit digit of large powers.',
    commonTrap: 'When n mod 4 = 0, use the 4th power, not the 0th.',
  },
  // ---- Modern Math: P&C ----
  {
    chapter: ['Modern Math', 'Permutations & Combinations'],
    title: 'Permutations',
    latex: '^{n}P_{r} = \\dfrac{n!}{(n-r)!}',
    plainText: 'nPr = n!/(n-r)!',
    description: 'Ordered arrangements.',
    whenToUse: 'Order matters (arrangements, rankings).',
    commonTrap: 'Using P when order does not matter (should be C).',
  },
  {
    chapter: ['Modern Math', 'Permutations & Combinations'],
    title: 'Combinations',
    latex: '^{n}C_{r} = \\dfrac{n!}{r!\\,(n-r)!}',
    plainText: 'nCr = n!/(r!(n-r)!)',
    description: 'Unordered selections.',
    whenToUse: 'Order does not matter (committees, subsets).',
    commonTrap: 'Forgetting the r! that removes ordering.',
  },
  {
    chapter: ['Modern Math', 'Permutations & Combinations'],
    title: 'Circular arrangements',
    latex: '(n-1)!',
    plainText: '(n-1)! for a circle',
    description: 'Distinct arrangements around a circle.',
    whenToUse: 'Round-table seating.',
    commonTrap: 'For reflectable arrangements (necklaces) divide by 2.',
  },
  // ---- Modern Math: Probability ----
  {
    chapter: ['Modern Math', 'Probability'],
    title: 'Basic probability',
    latex: 'P(E) = \\dfrac{\\text{favourable}}{\\text{total}}',
    plainText: 'P = favourable/total',
    description: 'Equally likely outcomes.',
    whenToUse: 'Finite equally-likely sample space.',
    commonTrap: 'Miscounting the total sample space.',
  },
  {
    chapter: ['Modern Math', 'Probability'],
    title: 'Addition rule',
    latex: 'P(A\\cup B) = P(A) + P(B) - P(A\\cap B)',
    plainText: 'P(A or B)=P(A)+P(B)-P(A and B)',
    description: 'Inclusion–exclusion for two events.',
    whenToUse: 'Union of possibly overlapping events.',
    commonTrap: 'Forgetting to subtract the intersection.',
  },
  // ---- Modern Math: Set Theory ----
  {
    chapter: ['Modern Math', 'Set Theory & Venn Diagrams'],
    title: 'Two-set inclusion–exclusion',
    latex: '|A\\cup B| = |A| + |B| - |A\\cap B|',
    plainText: '|A∪B| = |A|+|B|-|A∩B|',
    description: 'Count of a union.',
    whenToUse: 'Overlapping groups (surveys).',
    commonTrap: 'Double-counting the overlap.',
  },
  {
    chapter: ['Modern Math', 'Set Theory & Venn Diagrams'],
    title: 'Three-set inclusion–exclusion',
    latex: '|A\\cup B\\cup C| = \\sum|A| - \\sum|A\\cap B| + |A\\cap B\\cap C|',
    plainText: '|A∪B∪C| = singles - pairs + triple',
    description: 'Union of three sets.',
    whenToUse: 'Three overlapping categories.',
    commonTrap: 'Sign error: add back the triple intersection.',
  },
];

/** Build seeded Formula[] with stable ids so re-seeding is idempotent. */
export function buildSeedFormulas(): Formula[] {
  return QA.map((f) => {
    const chapterId = chapterSlug('QA', f.chapter[0], f.chapter[1]);
    return {
      id: `${chapterId}-f-${slugify(f.title)}`,
      chapterId,
      title: f.title,
      latex: f.latex,
      plainText: f.plainText,
      description: f.description,
      whenToUse: f.whenToUse,
      commonTrap: f.commonTrap,
      isSeeded: true,
      isStarred: false,
      createdAt: 0,
    };
  });
}
